/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package repositories;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class UserManagerModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UserManagerModel\",\"namespace\":\"repositories\",\"fields\":[{\"name\":\"userName\",\"type\":\"string\"},{\"name\":\"userEmail\",\"type\":\"string\"},{\"name\":\"userContact\",\"type\":\"string\"},{\"name\":\"uuid\",\"type\":\"string\"},{\"name\":\"address\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"landMark\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"secondContact\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence userName;
  @Deprecated public java.lang.CharSequence userEmail;
  @Deprecated public java.lang.CharSequence userContact;
  @Deprecated public java.lang.CharSequence uuid;
  @Deprecated public java.lang.CharSequence address;
  @Deprecated public java.lang.CharSequence landMark;
  @Deprecated public java.lang.CharSequence secondContact;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public UserManagerModel() {}

  /**
   * All-args constructor.
   */
  public UserManagerModel(java.lang.CharSequence userName, java.lang.CharSequence userEmail, java.lang.CharSequence userContact, java.lang.CharSequence uuid, java.lang.CharSequence address, java.lang.CharSequence landMark, java.lang.CharSequence secondContact) {
    this.userName = userName;
    this.userEmail = userEmail;
    this.userContact = userContact;
    this.uuid = uuid;
    this.address = address;
    this.landMark = landMark;
    this.secondContact = secondContact;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return userName;
    case 1: return userEmail;
    case 2: return userContact;
    case 3: return uuid;
    case 4: return address;
    case 5: return landMark;
    case 6: return secondContact;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: userName = (java.lang.CharSequence)value$; break;
    case 1: userEmail = (java.lang.CharSequence)value$; break;
    case 2: userContact = (java.lang.CharSequence)value$; break;
    case 3: uuid = (java.lang.CharSequence)value$; break;
    case 4: address = (java.lang.CharSequence)value$; break;
    case 5: landMark = (java.lang.CharSequence)value$; break;
    case 6: secondContact = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'userName' field.
   */
  public java.lang.CharSequence getUserName() {
    return userName;
  }

  /**
   * Sets the value of the 'userName' field.
   * @param value the value to set.
   */
  public void setUserName(java.lang.CharSequence value) {
    this.userName = value;
  }

  /**
   * Gets the value of the 'userEmail' field.
   */
  public java.lang.CharSequence getUserEmail() {
    return userEmail;
  }

  /**
   * Sets the value of the 'userEmail' field.
   * @param value the value to set.
   */
  public void setUserEmail(java.lang.CharSequence value) {
    this.userEmail = value;
  }

  /**
   * Gets the value of the 'userContact' field.
   */
  public java.lang.CharSequence getUserContact() {
    return userContact;
  }

  /**
   * Sets the value of the 'userContact' field.
   * @param value the value to set.
   */
  public void setUserContact(java.lang.CharSequence value) {
    this.userContact = value;
  }

  /**
   * Gets the value of the 'uuid' field.
   */
  public java.lang.CharSequence getUuid() {
    return uuid;
  }

  /**
   * Sets the value of the 'uuid' field.
   * @param value the value to set.
   */
  public void setUuid(java.lang.CharSequence value) {
    this.uuid = value;
  }

  /**
   * Gets the value of the 'address' field.
   */
  public java.lang.CharSequence getAddress() {
    return address;
  }

  /**
   * Sets the value of the 'address' field.
   * @param value the value to set.
   */
  public void setAddress(java.lang.CharSequence value) {
    this.address = value;
  }

  /**
   * Gets the value of the 'landMark' field.
   */
  public java.lang.CharSequence getLandMark() {
    return landMark;
  }

  /**
   * Sets the value of the 'landMark' field.
   * @param value the value to set.
   */
  public void setLandMark(java.lang.CharSequence value) {
    this.landMark = value;
  }

  /**
   * Gets the value of the 'secondContact' field.
   */
  public java.lang.CharSequence getSecondContact() {
    return secondContact;
  }

  /**
   * Sets the value of the 'secondContact' field.
   * @param value the value to set.
   */
  public void setSecondContact(java.lang.CharSequence value) {
    this.secondContact = value;
  }

  /** Creates a new UserManagerModel RecordBuilder */
  public static repositories.UserManagerModel.Builder newBuilder() {
    return new repositories.UserManagerModel.Builder();
  }
  
  /** Creates a new UserManagerModel RecordBuilder by copying an existing Builder */
  public static repositories.UserManagerModel.Builder newBuilder(repositories.UserManagerModel.Builder other) {
    return new repositories.UserManagerModel.Builder(other);
  }
  
  /** Creates a new UserManagerModel RecordBuilder by copying an existing UserManagerModel instance */
  public static repositories.UserManagerModel.Builder newBuilder(repositories.UserManagerModel other) {
    return new repositories.UserManagerModel.Builder(other);
  }
  
  /**
   * RecordBuilder for UserManagerModel instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UserManagerModel>
    implements org.apache.avro.data.RecordBuilder<UserManagerModel> {

    private java.lang.CharSequence userName;
    private java.lang.CharSequence userEmail;
    private java.lang.CharSequence userContact;
    private java.lang.CharSequence uuid;
    private java.lang.CharSequence address;
    private java.lang.CharSequence landMark;
    private java.lang.CharSequence secondContact;

    /** Creates a new Builder */
    private Builder() {
      super(repositories.UserManagerModel.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(repositories.UserManagerModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.userName)) {
        this.userName = data().deepCopy(fields()[0].schema(), other.userName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.userEmail)) {
        this.userEmail = data().deepCopy(fields()[1].schema(), other.userEmail);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.userContact)) {
        this.userContact = data().deepCopy(fields()[2].schema(), other.userContact);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.uuid)) {
        this.uuid = data().deepCopy(fields()[3].schema(), other.uuid);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.address)) {
        this.address = data().deepCopy(fields()[4].schema(), other.address);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.landMark)) {
        this.landMark = data().deepCopy(fields()[5].schema(), other.landMark);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.secondContact)) {
        this.secondContact = data().deepCopy(fields()[6].schema(), other.secondContact);
        fieldSetFlags()[6] = true;
      }
    }
    
    /** Creates a Builder by copying an existing UserManagerModel instance */
    private Builder(repositories.UserManagerModel other) {
            super(repositories.UserManagerModel.SCHEMA$);
      if (isValidValue(fields()[0], other.userName)) {
        this.userName = data().deepCopy(fields()[0].schema(), other.userName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.userEmail)) {
        this.userEmail = data().deepCopy(fields()[1].schema(), other.userEmail);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.userContact)) {
        this.userContact = data().deepCopy(fields()[2].schema(), other.userContact);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.uuid)) {
        this.uuid = data().deepCopy(fields()[3].schema(), other.uuid);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.address)) {
        this.address = data().deepCopy(fields()[4].schema(), other.address);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.landMark)) {
        this.landMark = data().deepCopy(fields()[5].schema(), other.landMark);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.secondContact)) {
        this.secondContact = data().deepCopy(fields()[6].schema(), other.secondContact);
        fieldSetFlags()[6] = true;
      }
    }

    /** Gets the value of the 'userName' field */
    public java.lang.CharSequence getUserName() {
      return userName;
    }
    
    /** Sets the value of the 'userName' field */
    public repositories.UserManagerModel.Builder setUserName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.userName = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'userName' field has been set */
    public boolean hasUserName() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'userName' field */
    public repositories.UserManagerModel.Builder clearUserName() {
      userName = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'userEmail' field */
    public java.lang.CharSequence getUserEmail() {
      return userEmail;
    }
    
    /** Sets the value of the 'userEmail' field */
    public repositories.UserManagerModel.Builder setUserEmail(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.userEmail = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'userEmail' field has been set */
    public boolean hasUserEmail() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'userEmail' field */
    public repositories.UserManagerModel.Builder clearUserEmail() {
      userEmail = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'userContact' field */
    public java.lang.CharSequence getUserContact() {
      return userContact;
    }
    
    /** Sets the value of the 'userContact' field */
    public repositories.UserManagerModel.Builder setUserContact(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.userContact = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'userContact' field has been set */
    public boolean hasUserContact() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'userContact' field */
    public repositories.UserManagerModel.Builder clearUserContact() {
      userContact = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'uuid' field */
    public java.lang.CharSequence getUuid() {
      return uuid;
    }
    
    /** Sets the value of the 'uuid' field */
    public repositories.UserManagerModel.Builder setUuid(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.uuid = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'uuid' field has been set */
    public boolean hasUuid() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'uuid' field */
    public repositories.UserManagerModel.Builder clearUuid() {
      uuid = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'address' field */
    public java.lang.CharSequence getAddress() {
      return address;
    }
    
    /** Sets the value of the 'address' field */
    public repositories.UserManagerModel.Builder setAddress(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.address = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'address' field has been set */
    public boolean hasAddress() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'address' field */
    public repositories.UserManagerModel.Builder clearAddress() {
      address = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'landMark' field */
    public java.lang.CharSequence getLandMark() {
      return landMark;
    }
    
    /** Sets the value of the 'landMark' field */
    public repositories.UserManagerModel.Builder setLandMark(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.landMark = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'landMark' field has been set */
    public boolean hasLandMark() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'landMark' field */
    public repositories.UserManagerModel.Builder clearLandMark() {
      landMark = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'secondContact' field */
    public java.lang.CharSequence getSecondContact() {
      return secondContact;
    }
    
    /** Sets the value of the 'secondContact' field */
    public repositories.UserManagerModel.Builder setSecondContact(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.secondContact = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'secondContact' field has been set */
    public boolean hasSecondContact() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'secondContact' field */
    public repositories.UserManagerModel.Builder clearSecondContact() {
      secondContact = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    public UserManagerModel build() {
      try {
        UserManagerModel record = new UserManagerModel();
        record.userName = fieldSetFlags()[0] ? this.userName : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.userEmail = fieldSetFlags()[1] ? this.userEmail : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.userContact = fieldSetFlags()[2] ? this.userContact : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.uuid = fieldSetFlags()[3] ? this.uuid : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.address = fieldSetFlags()[4] ? this.address : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.landMark = fieldSetFlags()[5] ? this.landMark : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.secondContact = fieldSetFlags()[6] ? this.secondContact : (java.lang.CharSequence) defaultValue(fields()[6]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
